### ISSUE TITLE
Parameters on PASCAL-Context

### ISSUE THREAD

**Issue by innovator-zero** [yangyangxu0/DeMT#2]
Hi, I notice that you have provided information on the number of parameters for models trained on NYUD, and I wonder if you might be able to share similar information for PASCAL-Context, which involves one additional task. Could you kindly share them with us? Thanks!

**Comment by yangyangxu0** [comment]
Our GFLOP and parameter on PASCAL-Context dataset: 
DeMT-T(94.5G 33.0M), DeMT-S(112.3G 54.3M), DeMT-B(143.0G 94.9M).
 Hope these can help you.

**Comment by innovator-zero** [comment]
Received. Thanks a lot!
