### ISSUE TITLE
Question about Deformable Mixer

### ISSUE THREAD

**Issue by Yiir-1** [yangyangxu0/DeMT#3]
Thanks for the good work! I have a question about Deformable Mixer, when i read the paper, it said the channel-aware Mixing is behind the Spatial-aware Deformable,like this
![image](https://user-images.githubusercontent.com/81577270/223097876-80a8cf40-6e97-42a6-b815-9a822a63c423.png)
but when i read the code,it's like the model first run Spatial-aware Deformable , and then channel-aware Mixing 
https://github.com/yangyangxu0/DeMT/blob/889ccaa4847a01e5f5eb4ae6c9f50a6647867fc9/src/model/heads/demt_head.py#L88

![image](https://user-images.githubusercontent.com/81577270/223098965-11b56b3f-fb64-4a42-befd-d094a873c478.png)

Maybe my understanding is wrong, but I'm very confused about here .

**Comment by yangyangxu0** [comment]
Since there is a lot of code for iteration, this detail was ignored when releasing code. Thank you for your notice. We have updated it.
